### ISSUE TITLE
smpl_model_folder

### ISSUE THREAD

**Issue by yuxwind** [QianliM/CAPE#1]
Great work! To run the demo, we need to set the path to SMPL model folder.

```
python main.py --config configs/config.yaml --mode demo --vis_demo 1 --smpl_model_folder <path to SMPL model folder>
```
However, I didn't find the SMPL files in this repo(I may miss it). Could you provide the files or the links to download them? Thanks!

**Comment by QianliM** [comment]
Hi, the SMPL models are to be called by the smplx module. Therefore, simply follow the instructions of the [smplx github page](https://github.com/vchoutas/smplx#downloading-the-model) to download and process the SMPL model files (for this repo you only need the SMPL model, no need for SMPL-H or SMPLX). Then the top-level directory ("models") in [this structural plot](https://github.com/vchoutas/smplx#model-loading) is the smpl_model_folder.

**Comment by yuxwind** [comment]
Thanks! I followed your instruction and have downloaded the files.
