### ISSUE TITLE
RuntimeError: size of dimension does not match previous size, operand 1, dim 2

### ISSUE THREAD

**Issue by Demohai** [QianliM/CAPE#10]
I followed all your README steps to build the project.
Using all your pre-trained models and corresponding config files will get the RuntimeError.
![image](https://user-images.githubusercontent.com/35857069/94903585-9ab00b00-04cc-11eb-8e7a-6ef8f0df4ab0.png)
the error happened on this line of code:
![image](https://user-images.githubusercontent.com/35857069/94903702-c03d1480-04cc-11eb-861e-7e16a225ed0a.png)
where the shape of betas and shape_disps are (1, 10) and (6890, 3, 300).
I want to know where does the error happen? Thanks a lot!

**Comment by QianliM** [comment]
Hi, here's the reason: SMPL has recently updated a new version with all 300 shape parameters (i.e. dimension of betas) -- i guess that's the version you have downloaded? Previously only the first 10 beta params (i.e. the first 10 PCA coefficients of the shape space) are released and that's what we used in CAPE. Also the default beta dimension is still 10 in the smplx package at the moment. Hence this error happens.

You can try with your current model taking only the first 10 PCs of the shapedirs by adding `self.smpl_model.shapedirs = self.smpl_model.shapedirs[...,:10]` after [loading the SMPL model](https://github.com/QianliM/CAPE/blob/9c466419339c218a96d54c241f6c02ef8be8d770/demos.py#L22). Please let me know if this does not work.
Or the 100% work solution would be downloading the SMPL model version 1.0.0 for (10 shape PCs).

**Comment by Demohai** [comment]
@QianliM  yes, it does work! Thanks a lot.
