### ISSUE TITLE
No module named 'psbody'

### ISSUE THREAD

**Issue by FD-MINGJIE** [qianlim/CAPE#13]
WoW! Awesome work! 
I have some trouble with your released code:
1. ModuleNotFoundError: No module named 'psbody'. I did'n find the psbody.py
```
  File "main.py", line 8, in <module>
    from psbody.mesh import Mesh
ModuleNotFoundError: No module named 'psbody'
```
2. I'm pretty interested in the SMPL and CAPE, so could you send me a copy of code about SMPL in tf? It'll be important for me to learn the CAPE.
Thanks for sharing the gread work!

**Comment by QianliM** [comment]
Hi, psbody.mesh package is avaialble [here](https://github.com/MPI-IS/mesh).
The original SMPL code is unfortunately not available in TF. But the latest members from the SMPL family are good sources to look at: check out the [SMPL-X model (pytorch, code includes SMPL)](https://github.com/vchoutas/smplx) and the [STAR (pytorch and tf2.0)](https://github.com/ahmedosman/STAR).
