### ISSUE TITLE
Mapping 3D T-shirt to Z variable

### ISSUE THREAD

**Issue by lokender** [qianlim/CAPE#14]
How can we map an unknown T-Shirt style to the Z variable? 
Basically, Instead of sampling, I want to dress a person in a specific 3D garment (say T-shirt). Is it possible with the CAPE ?.

**Comment by QianliM** [comment]
Yes, if the garment type is given, you can simply fix the 1-hot garment code to be that type, as well as fixing the decoder weights and optimize the z to minimize the point-to-mesh (or chamfer etc.) distance to the target scan (these loss terms and the optimization process is not provided in this repo though).
