### ISSUE TITLE
Pytorch in requirements

### ISSUE THREAD

**Issue by old-school-kid** [QianliM/CAPE#19]
Hi! Great work and thank you for making the code public. 
I think the `torch==1.2.0` is an overhead in the requirements.txt file. Would be helpful for the end-user if the over head can be removed.
TIA

**Comment by qianlim** [comment]
Hi! Thanks for the suggestion. Pytorch is actually a dependency of the smplx package, which is used to repose the meshes in the demo. So when installing smplx, pytorch will be automatically installed anyway.

**Comment by old-school-kid** [comment]
Ah, thank you for clearing that.
